#!/usr/bin/env bash
# Copyright 2016 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

readonly SCRIPT_ROOT="$(dirname ${BASH_SOURCE[0]} )"
readonly TOOL_NAME=$(basename "$0")

echo "${BASH_SOURCE[0]}"
echo "$($(dirname ${BASH_SOURCE[0]} ) && pwd)"
echo "${SCRIPT_ROOT}"
source "${SCRIPT_ROOT}/exec_tool.sh"
